# Catálogo de "Mi espacio" que el backend acepta al guardar la personalización.
# Debe coincidir con frontend/src/profile/catalog.js.

DEFAULT_PROFILE_THEME = "fribuk"
MAX_EMOJI_DECORATIONS = 3
MAX_AMBIENT_DECORATIONS = 1

# Tema -> colores de acento permitidos (los que mantienen un contraste legible).
PROFILE_THEME_ACCENTS = {
    "fribuk": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "gotico": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "fantasia": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "minimalista": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "naturaleza": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "romance": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "espacial": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "vintage": ("rojo", "ambar", "lima", "verde", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "comics": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "cyberpunk": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "dark-academia": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "y2k": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "cottagecore": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "art-deco": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "retro": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "kawaii": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "horror": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "steampunk": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "urbano": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "neon": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "fairycore": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
    "noir": ("rojo", "naranja", "ambar", "lima", "verde", "turquesa", "cielo", "azul", "violeta", "magenta", "rosa", "grafito"),
}

# Decoración -> tipo: "emoji" (de OpenMoji; el id es el código del emoji),
# "ambient" (fondo sutil) u "option" (mostrar los emojis como pegatinas).
PROFILE_DECORATIONS = {
    "2764": "emoji",
    "1F5A4": "emoji",
    "1F49C": "emoji",
    "1F495": "emoji",
    "1F494": "emoji",
    "2728": "emoji",
    "1F31F": "emoji",
    "1F525": "emoji",
    "1F308": "emoji",
    "1F319": "emoji",
    "2B50": "emoji",
    "2600": "emoji",
    "26A1": "emoji",
    "2744": "emoji",
    "1FA90": "emoji",
    "1F98B": "emoji",
    "1F338": "emoji",
    "1F339": "emoji",
    "1F33B": "emoji",
    "1F340": "emoji",
    "1F344": "emoji",
    "1F342": "emoji",
    "1F431": "emoji",
    "1F408-200D-2B1B": "emoji",
    "1F43A": "emoji",
    "1F98A": "emoji",
    "1F430": "emoji",
    "1F989": "emoji",
    "1F40D": "emoji",
    "1F409": "emoji",
    "1F984": "emoji",
    "1F9DA": "emoji",
    "1F52E": "emoji",
    "1F451": "emoji",
    "2694": "emoji",
    "1F3F0": "emoji",
    "1FA84": "emoji",
    "1F480": "emoji",
    "1F47B": "emoji",
    "1F987": "emoji",
    "1F577": "emoji",
    "1F56F": "emoji",
    "1F4DA": "emoji",
    "1F4D6": "emoji",
    "1F58B": "emoji",
    "2615": "emoji",
    "1F3A7": "emoji",
    "1F3A8": "emoji",
    "1F3AE": "emoji",
    "1F353": "emoji",
    "lluvia": "ambient",
    "nieve": "ambient",
    "olas": "ambient",
    "telaranas": "ambient",
    "vhs": "ambient",
    "digital": "ambient",
    "pegatinas": "option",
}
